server:
  port: 10111

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/onldb?useUnicode=true&characterEncoding=utf-8
    username: ls_firstdb
    password: ls130050
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    platform: mysql
    filters : stat,wall,log4j2
    maxActive : 100
    initialSize : 100
    maxWait : 60000
    minIdle : 0
    timeBetweenEvictionRunsMillis : 60000
    minEvictableIdleTimeMillis : 300000
    validationQuery : select 'x'
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    poolPreparedStatements : true
    maxOpenPreparedStatements : 20

mybatis:
  type-aliases-package: com.intpict.demo.entity
  mapper-locations: classpath:sqlmap/*.xml

