spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onldb?useUnicode=true&characterEncoding=utf-8
    username: ls_firstdb
    password: ls130050
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql

mybatis:
  type-aliases-package: com.intpict.demo.entity
  mapper-locations: classpath:sqlmap/*.xml
